# Generated by Django 5.2.4 on 2025-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('MERCHANT', 'Merchant'), ('LENDER', 'Lender'), ('EMPLOYER', 'Employer'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='PERSON', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or business registration number', max_length=50, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
