# Generated by Django 5.2.4 on 2025-09-01 06:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom (RRULE)')], default='MONTHLY', max_length=20)),
                ('recurrence_rule', models.TextField(blank=True, help_text='RRULE string for custom frequencies', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for recurring payments', null=True)),
                ('next_due_date', models.DateField()),
                ('last_executed_date', models.DateField(blank=True, null=True)),
                ('auto_execute', models.BooleanField(default=False, help_text='Automatically create transactions on due date')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3, help_text='Days before due date to send reminder')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Maximum number of times to execute', null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('payee_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('tags', models.ManyToManyField(blank=True, to='finance.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('SCHEDULED_PAYMENT', 'Scheduled Payment'), ('LOAN_EMI', 'Loan EMI'), ('BILL_DUE', 'Bill Due'), ('BUDGET_ALERT', 'Budget Alert'), ('INCOME_EXPECTED', 'Income Expected')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('channels', models.JSONField(default=list, help_text='List of channels to send reminder')),
                ('send_at', models.DateTimeField(help_text='When to send the reminder')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scheduled_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.scheduledpayment')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPaymentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('auto_executed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scheduled_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduling.scheduledpayment')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-execution_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledpayment',
            index=models.Index(fields=['user', 'status'], name='scheduling__user_id_cc868d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpayment',
            index=models.Index(fields=['user', 'next_due_date'], name='scheduling__user_id_72735b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpayment',
            index=models.Index(fields=['user', 'auto_execute'], name='scheduling__user_id_a1f7ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledpayment',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['user', 'status'], name='scheduling__user_id_cd0db6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['user', 'send_at'], name='scheduling__user_id_3218c7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['type', 'status'], name='scheduling__type_966cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpaymentexecution',
            index=models.Index(fields=['scheduled_payment', 'execution_date'], name='scheduling__schedul_6f9c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpaymentexecution',
            index=models.Index(fields=['user', 'execution_date'], name='scheduling__user_id_0d59cd_idx'),
        ),
    ]
