# Generated by Django 5.2.4 on 2025-09-01 06:47

import django.db.models.deletion
import statements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('MONTHLY', 'Monthly Statement'), ('QUARTERLY', 'Quarterly Statement'), ('YEARLY', 'Yearly Statement'), ('CUSTOM', 'Custom Period Statement'), ('ACCOUNT', 'Account Statement'), ('CATEGORY', 'Category Statement')], default='MONTHLY', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('include_transfers', models.BooleanField(default=True)),
                ('include_inactive', models.BooleanField(default=False, help_text='Include soft-deleted transactions')),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_attachments', models.BooleanField(default=False, help_text='Include transaction attachments in ZIP')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=statements.models.statement_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('summary_data', models.JSONField(blank=True, help_text='Statement summary statistics', null=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('transaction_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('accounts', models.ManyToManyField(blank=True, help_text='Specific accounts to include', to='finance.account')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('categories', models.ManyToManyField(blank=True, help_text='Specific categories to include', to='finance.category')),
                ('contacts', models.ManyToManyField(blank=True, help_text='Specific contacts to include', to='contacts.contact')),
                ('tags', models.ManyToManyField(blank=True, help_text='Specific tags to include', to='finance.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='statements__user_id_662c74_idx'), models.Index(fields=['user', 'period_start', 'period_end'], name='statements__user_id_1734f6_idx'), models.Index(fields=['user', 'type'], name='statements__user_id_492463_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='statement_templates/')),
                ('header_text', models.TextField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#64748B', help_text='Hex color code', max_length=7)),
                ('font_family', models.CharField(default='Arial', help_text='Font family name', max_length=50)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_transaction_list', models.BooleanField(default=True)),
                ('include_category_breakdown', models.BooleanField(default=True)),
                ('include_account_breakdown', models.BooleanField(default=True)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A4', max_length=10)),
                ('page_orientation', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=10)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='statement_templates/')),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
