# Generated by Django 5.2.4 on 2025-09-01 06:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('CAR', 'Car Loan'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], default='PERSONAL', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term_months', models.PositiveIntegerField(help_text='Loan term in months')),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('emi_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month for EMI payment', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('next_emi_date', models.DateField()),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DEFAULTED', 'Defaulted'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('auto_create_emi', models.BooleanField(default=False, help_text='Automatically create EMI transactions')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3, help_text='Days before EMI due date to send reminder')),
                ('loan_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='Account used for EMI payments', on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('lender_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_emi_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extra_principal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'next_emi_date'], name='loans_loan_user_id_3b0176_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'lender_contact'], name='loans_loan_user_id_e2228c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='emipayment',
            index=models.Index(fields=['loan', 'payment_date'], name='loans_emipa_loan_id_d522c6_idx'),
        ),
        migrations.AddIndex(
            model_name='emipayment',
            index=models.Index(fields=['user', 'payment_date'], name='loans_emipa_user_id_b2d187_idx'),
        ),
    ]
