# Generated by Django 5.2.4 on 2025-09-01 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('BUDGET_ALERT', 'Budget Alert'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('INCOME_RECEIVED', 'Income Received'), ('INCOME_OVERDUE', 'Income Overdue'), ('LOAN_EMI_DUE', 'Loan EMI Due'), ('LOAN_EMI_OVERDUE', 'Loan EMI Overdue'), ('STATEMENT_READY', 'Statement Ready'), ('ACCOUNT_LOW_BALANCE', 'Account Low Balance'), ('GOAL_ACHIEVED', 'Goal Achieved'), ('TRANSACTION_LARGE', 'Large Transaction'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('SECURITY_ALERT', 'Security Alert'), ('GENERAL', 'General')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('SMS', 'SMS')], default='IN_APP', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When to send the notification')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the notification expires', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Additional notification data')),
                ('action_buttons', models.JSONField(default=list, help_text='List of action buttons for the notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('RETRIED', 'Retried'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('BUDGET_ALERT', 'Budget Alert'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('INCOME_RECEIVED', 'Income Received'), ('INCOME_OVERDUE', 'Income Overdue'), ('LOAN_EMI_DUE', 'Loan EMI Due'), ('LOAN_EMI_OVERDUE', 'Loan EMI Overdue'), ('STATEMENT_READY', 'Statement Ready'), ('ACCOUNT_LOW_BALANCE', 'Account Low Balance'), ('GOAL_ACHIEVED', 'Goal Achieved'), ('TRANSACTION_LARGE', 'Large Transaction'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('SECURITY_ALERT', 'Security Alert'), ('GENERAL', 'General')], max_length=30)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('DISABLED', 'Disabled')], default='IMMEDIATE', max_length=20)),
                ('min_priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', help_text='Minimum priority level to receive notifications', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('BUDGET_ALERT', 'Budget Alert'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('INCOME_RECEIVED', 'Income Received'), ('INCOME_OVERDUE', 'Income Overdue'), ('LOAN_EMI_DUE', 'Loan EMI Due'), ('LOAN_EMI_OVERDUE', 'Loan EMI Overdue'), ('STATEMENT_READY', 'Statement Ready'), ('ACCOUNT_LOW_BALANCE', 'Account Low Balance'), ('GOAL_ACHIEVED', 'Goal Achieved'), ('TRANSACTION_LARGE', 'Large Transaction'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('SECURITY_ALERT', 'Security Alert'), ('GENERAL', 'General')], max_length=30)),
                ('title_template', models.CharField(help_text='Title template with placeholders', max_length=200)),
                ('message_template', models.TextField(help_text='Message template with placeholders')),
                ('email_subject_template', models.CharField(blank=True, max_length=200, null=True)),
                ('email_html_template', models.TextField(blank=True, null=True)),
                ('push_title_template', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_template', models.CharField(blank=True, max_length=160, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('action_buttons_template', models.JSONField(default=list, help_text='Template for action buttons')),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be modified')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'channel'], name='notificatio_user_id_af98f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at', 'status'], name='notificatio_schedul_963ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'action'], name='notificatio_notific_d42cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['action', 'timestamp'], name='notificatio_action_2839e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('user', 'name', 'notification_type')},
        ),
    ]
